import type { Metadata } from "next";

import "./globals.css";

import MobileContainer from "./components/MobileContainer";
import { pretendard } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body
        className={`${pretendard.variable} ${pretendard.variable} antialiased`}
      >
        <MobileContainer>{children}</MobileContainer>
      </body>
    </html>
  );
}
